name: mr_assignment1 
channels:
  - defaults
  - open3d-admin
dependencies:
  - numpy
  - scipy
  - matplotlib
  - plotly
  - ipython
  - jupyter
  - opencv-python
  - sympy
  - nose
  - pandas
  - open3d
